name: Test

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:  # allow manual invocation

jobs:
  test:
    name: Test (Python ${{ matrix.python-version }})
    permissions:
      contents: read
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        python-version: ['3.12', '3.13', '3.14']
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
        with:
          python-version: ${{ matrix.python-version }}

      # Keep steps in sync with justfile
      - run: just -v sync --locked
      - run: just -v lint
      - run: just -v types
      - run: just -v test
      - run: just -v docs
      - run: just -v dist

      - uses: actions/upload-pages-artifact@v4.0.0
        if: matrix.python-version == '3.12'
        with:
          path: dist/docs/

  deploy-github-pages:
    if: >-
      (github.event_name == 'push' || github.event_name == 'workflow_dispatch')
      && github.ref == 'refs/heads/main'
    needs: test
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      pages: write
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/deploy-pages@v4.0.5
